name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: |
          cd forest_of_longing
          npm ci

      - name: Build
        run: |
          cd forest_of_longing
          npm run build
        env:
          PUBLIC_URL: /shabdarth/forest_of_longing

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: forest_of_longing/build
          branch: gh-pages
          target-folder: forest_of_longing
          